[project]
name = "aie"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "chsumin0316-oss", email = "chsumin0316@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.141.1",
]

[project.scripts]
aie = "aie:main"

[build-system]
requires = ["uv_build>=0.12.11,<0.13.0"]
build-backend = "uv_build"
